<?php
namespace mall\controllers;

use common\models\frontend\User;
use backend\models\AdGoodsAttr;
use mall\models\AdAttrs;
use mall\models\AdCart;
use mall\models\AddressBook;
use mall\models\AdGoods;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\controllers\CshopController;
use mall\models\PasswordResetRequestForm;
use mall\models\ResetPasswordForm;
use mall\models\SignupForm;
use mall\models\ContactForm;
use mall\share\Curl;
use mall\share\Functions;
use yii\helpers\Url;
use mall\models\AddressBookSearch;

/**
 * Site controller
 */
class PayController extends CshopController
{
    const EXPIRE_TIME = 3600;
    private $_curl = '';
    private $_functions = '';
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                //'only' => ['login', 'signup'],
                'only' => ['login'],
                'rules' => [
                    [
                        //'actions' => ['signup'],
                        'allow' => false,
                        'roles' => ['@'],
                    ],
                    /*[
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],*/
                ],
            ],
            /*'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],*/
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->_curl = new Curl();
        $this->_functions = new Functions();;
    }

    public function actionIndex() {
        $this->layout = 'index2';
        $url = Yii::$app->params['api.cart.pay'] . Yii::$app->session->readSession('user:' . Yii::$app->user->id . ':access_token');
        $res = $this->_curl->getCart($url);
        $api_result = json_decode($res[0]);
        if($api_result[0] != 'ok') {
            echo "<pre>";
            print_r($api_result);
            exit;
        }
        Yii::$app->getSession()->setFlash('success', '付款成功！');
        return $this->redirect(Yii::$app->request->getReferrer());
    }
}
