<?php
namespace mall\controllers;

use common\models\frontend\User;
use backend\models\AdGoodsAttr;
use mall\models\AdAttrs;
use mall\models\AdCart;
use mall\models\AddressBook;
use mall\models\AdGoods;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\controllers\CshopController;
use mall\models\PasswordResetRequestForm;
use mall\models\ResetPasswordForm;
use mall\models\SignupForm;
use mall\models\ContactForm;
use mall\share\Curl;
use mall\share\Functions;
use yii\helpers\Url;
use mall\models\AddressBookSearch;

/**
 * Site controller
 */
class UserController extends CshopController
{
    const EXPIRE_TIME = 3600;
    private $_curl = '';
    private $_functions = '';
    const ORDER_STATE_PAYED = 1;
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login'],
                'rules' => [
                    [
                        'allow' => false,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->_curl = Curl::getInstance();
        $this->_functions = Functions::getInstance();
    }

    /*
     * 用户信息
     */
    public function actionProfile() {
        /*
         * 用户注册的时候为其默认生成一个随机的昵称
         */
        $this->layout = 'page';
        $offset = 0;
        $limit = 10;
        $query_condition = '&offset=' . $offset . '&limit=' . $limit;
        $url_user = Yii::$app->params['api.user.info'] . Yii::$app->session->readSession('user:' . Yii::$app->user->id . ':access_token');
        $url_shop = Yii::$app->params['api.cart.get'] . Yii::$app->session->readSession('user:' . Yii::$app->user->id . ':access_token') . '&state=' . self::ORDER_STATE_PAYED . $query_condition;
        $url_views = Yii::$app->params['api.log.views'] . Yii::$app->session->readSession('user:' . Yii::$app->user->id . ':access_token');
        $url_views_more = Yii::$app->params['api.log.views.most'] . Yii::$app->session->readSession('user:' . Yii::$app->user->id . ':access_token') . '&detail=0';
        $url_recommend = Yii::$app->params['api.log.recommend'] . Yii::$app->session->readSession('user:' . Yii::$app->user->id . ':access_token') . '&detail=0';

        //获取用户看过的商品的数量
        $res_views = $this->_curl->getCart($url_views);
        //获取用户看过的最多的产品
        $res_view_more = $this->_curl->getCart($url_views_more);
        //推荐给用户的商品
        $res_recommend_goods = $this->_curl->getCart($url_recommend);
        //获取购买且付款的5条数据
        $res_shop = $this->_curl->getCart($url_shop);
        $res = $this->_curl->getUserInfo($url_user);
        $user_info = json_decode($res[0], true);

        $shop_info = json_decode($res_shop[0], true);
        $views_count = json_decode($res_views[0], true);
        $views_most = json_decode($res_view_more[0], true);
        $recommend_goods = json_decode($res_recommend_goods[0], true);
        return $this->render('profile',[
            'user_info' => $user_info,
            'shop_info' => $shop_info,
            'views_count' => $views_count,
            'views_most' => $views_most,
            'recommend_goods' => $recommend_goods
        ]);
    }

    public function actionEdit() {
        $this->layout = 'page';
        $model = new AddressBook();
        if ($post = Yii::$app->request->post()) {
            $url = Yii::$app->params['api.user.post'] . Yii::$app->session->readSession('user:' . Yii::$app->user->id . ':access_token');
            $res = $this->_curl->postCurl($url, json_encode($post));
            $api_result = json_decode($res[0], true);
            if($api_result[0] == 'error') {
                echo "<pre>";
                print_r($api_result[1]);
                exit;
            }
            Yii::$app->getSession()->setFlash('success', '修改数据成功');
            return $this->redirect(['user/profile']);
        } else {
            //获取用户默认值
            $url = Yii::$app->params['api.user.get'] . Yii::$app->session->readSession('user:' . Yii::$app->user->id . ':access_token');
            $res = $this->_curl->getUserInfo($url);
            $user_info = json_decode($res[0], true);
            return $this->render('edit',[
                'model' => $model,
                'user_info' => $user_info,
            ]);
        }
    }
}
