<?php
namespace api_goods\controllers;

use api_goods\models\AdCart;
use mall\models\AdGoods;
use Yii;
use common\controllers\ApicomController;
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;
use common\models\LoginForm;
use yii\data\Pagination;

/**
 * Site controller
 */
class GoodsController extends ApicomController
{
	public $enableCsrfValidation = false;
	public $_reids = '';

	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
		$this->_reids = Yii::$app->request->get();
	}

	/*
	 * 获取商品列表
	 * @offset 偏移量
	 * @limit限制条数
	 */
	public function actionList() {
		Yii::$app->request->get('page') ? $page = Yii::$app->request->get('page') : $page = 0;
		$query = (new \yii\db\Query())
				->select(['id', 'goods_name', 'current_original_price'])
				->from('ad_goods');
		$countQuery = clone $query;
		$goods_list = $query
				->offset($page * 18)
				->limit(18)
				->all();
		//$pages = new Pagination(['totalCount' => $countQuery->count()]);
		$data['total_page'] = $countQuery->count();
		$data['goods_list'] = $goods_list;
		return json_encode($data);
	}

	/*
	 * 获取首页顶部轮询商品
	 */
	public function actionTop3() {
		$goods_list = (new \yii\db\Query())
				->select(['id', 'goods_name', 'current_original_price'])
				->from('ad_goods')
				->limit(3)
				->all();
		return json_encode($goods_list);
	}
}























