<?php
namespace news\controllers;

use Yii;
use yii\web\Controller;
use common\controllers\CnewsController;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\frontend\LoginForm;
use common\controllers\SessionController;
use mall\models\SignupForm;
use common\models\frontend\User;
use mall\share\Curl;

/**
 * Site controller
 */
class SiteController extends CnewsController
{
    private $_curl = '';
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        $this->layout = 'index';
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->_curl =Curl::getInstance();
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        $this->layout = 'index';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if($model->load(Yii::$app->request->post()) && $model->login()) {
            //记录用户登录信息
            $log_info['login_ip'] = $_SERVER['REMOTE_ADDR'];
            $log_info['login_time'] = time();
            $log_info['login_sys'] = Yii::$app->params['news'];
            $res = User::find()->select(['access_token'])->where(['id' => Yii::$app->user->id])->one();
            $url = Yii::$app->params['api.log.login'] . $res->access_token;
            $res = $this->_curl->postCurl($url, json_encode($log_info));
            return $this->goBack();
        } else {
            //$this->layout = "main-copy";
//return $this->goHome();
            $model->password = '';
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }



    public function _actionLogin()
    {
        $this->layout = 'index';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if (Yii::$app->user->isGuest) {
            if($model->load(Yii::$app->request->post()) && $model->login()) {
                return $this->goBack();
            } else {
                //$this->layout = "main-copy";
                $model->password = '';
                return $this->render('login', [
                    'model' => $model,
                ]);
            }
        } else {
            echo 'site/login --> not isguest';exit;
            return $this->render('index');
        }
    }
    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionSignup()
    {
        $this->layout = 'index';
        $model = new SignupForm();
        if ($post = Yii::$app->request->post()) {
            //调用注册接口
            $url = Yii::$app->params['api.user.user.register'] . Yii::$app->params['loger_access_token'];
            $res = $this->_curl->postCurl($url, json_encode($post));
            $res1 = json_decode($res[0], true);
            if ($res1[0] == 100) {
                if ($res1[1]) {
                    //显示提示激活邮件信息，并且发送激活邮件
                    $url = Yii::$app->params['api.user.register'] . $res1[1];
                    $res = $this->_curl->getCart($url);
                    return $this->render('active', [
                    ]);
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }
}
